django_sns/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('allauth.urls')),
    path('', home, name="home"),
    path('users',include('users.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import *

app_name = "posts"
urlpatterns = [
    path('create/', create, name='create'),
    path('update/<int:id>/', update, name='update'),
    path('delete/<int:id>/', delete, name="delete"),

    #comments
    path('<int:post_id>/create_comment/', create_comment, name="create_comment"),
    path('<int:comment_id>/delete_comment/', delete_comment, name="delete_comment"),

    #likes
    path('<int:post_id>/post_like/', post_like, name="post_like"),
    path('like_list/', like_list, name="like_list"),
]

users/urls.py
from django.urls import path
from .views import follow_toggle, mypage

app_name='users'
urlpatterns=[
    path('<int:id>/follow_toggle', follow_toggle, name="follow_toggle"),
    path('<int:id>/mypage', mypage, name="mypage"),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=50, null=False)
    content = models.TextField()
    view_count = models.IntegerField(default=0)
    image = models.ImageField(upload_to="image/post", blank="true")
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    like_user_set = models.ManyToManyField(User, blank=True, related_name='like_user_set', through='Like')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def like_count(self):
        return self.like_user_set.count()


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete = models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Like(models.Model):
    post = models.ForeignKey(Post, on_delete = models.CASCADE)
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = (('user', 'post'))

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images', default="images/default/png")
    info = models.TextField(null=True, blank=True)
    followings = models.ManyToManyField("self", related_name="followers", symmetrical=False)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

posts/forms.py
#from django import forms
from django.forms import ModelForm
from .models import Post

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = {
            'title',
            'content',
            'image',
        }
        labels={
            'title' : {'제목'},
            'content' : {'내용'},
            'image' : {'이미지'},
        }
        help_texts={
            'title' : {'제목을 입력해주세요'},
            'content' : {'내용을 입력해주세요'},
        }
    def save(self, **kwargs):
        post = super().save(commit=False)
        post.user = kwargs.get('user', None)
        post.save()
        return post

django_sns/views.py
from django.shortcuts import render
from posts.models import Post, Comment
import pdb

def home(request):
    context = {
        'user': request.user,
        'posts': Post.objects.all(),
        'comments': Comment.objects.all()
    }
    return render(request, 'home.html', context)

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Comment
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import PostForm
import pdb


# Create your views here.
@login_required
def create(request):
    if request.method=="POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save(user=request.user)
        return redirect('home')
    else:
        form = PostForm()
    return render(request, 'posts/create.html', {'form':form})


@login_required
def update(request, id):
    post = get_object_or_404(Post, pk=id)
    if request.method == "POST":
        post.title = request.POST.get("title")
        post.content = request.POST.get("content")
        post.image = request.FILES.get("image")
        post.save()
        return redirect('home')
    return render(request, 'posts/update.html', {"post": post})
    

@login_required
def delete(request, id):
    post = get_object_or_404(Post, pk=id)
    post.delete()
    return redirect('home')


@login_required
def create_comment(request, post_id):
    if request.method == "POST":
        post = get_object_or_404(Post, pk=post_id)
        user = request.user
        content = request.POST.get('content')
        Comment.objects.create(content=content, user=user, post=post)
    return redirect('home')

@login_required
def delete_comment(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    comment.delete()
    return redirect('home')

@login_required
def post_like(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    
    if request.user in post.like_user_set.all():
        post.like_user_set.remove(request.user)
    else:
        post.like_user_set.add(request.user)

    return redirect('home')

@login_required
def like_list(request):
    likes = request.user.like_user_set.all()
    return render(request, 'posts/like_list.html', {'likes': likes})

users/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import User
from posts.models import Post
import pdb

# Create your views here.
@login_required
def follow_toggle(request, id):
    user = request.user
    followed_user = get_object_or_404(User, pk=id)
    is_follower = user.profile in followed_user.profile.followers.all()

    if is_follower:
        user.profile.followings.remove(followed_user.profile)
    else:
        user.profile.followings.add(followed_user.profile)

    return redirect('home')

def mypage(request, id):
    user = get_object_or_404(User, pk=id)
    
    context = {
        'posts' : Post.objects.filter(user=user),
        'followings' : user.profile.followings.all(),
        'followers' : user.profile.followers.all(),
    }

    return render(request, 'users/mypage.html', context)

posts/templates/comments/_comment.html
<li class="list-group-item" id="comment-{{ comment.pk }}">
    <p>
        <b>{{ comment.user.username }}</b>
        {% if user == comment.user %}
            <a href="{% url 'posts:delete_comment' comment.id %}" class="right comment-delete-button" id="comment-delete-{{ comment.pk }}" data-comment-id="{{ comment.pk }}">삭제</a>
        {% endif %}
    </p>
    <p>{{ comment.content }}</p>
</li>

posts/templates/posts/create.html
{% extends 'base.html' %}

{% block content %}

{% comment %}
<div class="container">
    <h2 class="mt-5">새로운 글 쓰기</h2>
    <form action="{% url 'posts:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label>글 제목</label>
            <input type="text" class="form-control" name="title" required>
        </div>
        <div class="form-group">
            <label>글 내용</label>
            <input type="text" class="form-control" name="content" required>
        </div>
        <div class="form-group">
            <label>이미지</label>
            <input type="file" name="image" multiple>
        </div>
        <input type="submit" value="작성하기" class="btn btn-primary">
    </form>
</div>
{% endcomment %}

<div>
    <form action="{% url 'posts:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="작성하기" class="btn btn-primary">
    </form>
</div>
{% endblock %}

posts/templates/posts/update.html
{% extends 'base.html' %}

{% block content %}
<div class="row mt-5">
    <h1>글 수정하기</h1>
    <div class="card col-12 pb-4">
        <div class="card-content">
            <br>
            <form action="{% url 'posts:update' post.id %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label>글 제목</label>
                    <input type="text" class="form-control" name="title" value="{{ post.title }}" required>
                </div>
                <div class="form-group">
                    <label>글 내용</label>
                    <input type="text" class="form-control" name="content" value={{ post.content }} required>
                </div>
                <div class="form-group">
                    <label>이미지</label>
                    <input type="file" name="image">
                </div>

                <input type="submit" class="btn btn-primary" value="수정하기">
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"/>
        <title>SNS</title>
    </head>
    <body>
        {% include 'shared/_navbar.html' %}
        
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
        <script src="{% static 'js/project.js' %}"></script>
    </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
<div class="sns-container">
    <div class="row">
        <div class="col-8">
            <div class="card mt-4 mb-4">
                여기는 내가 추가한 follow한 사람들 스토리 들어감
            </div>
            {% for post in posts %}
                <div class="card mb-5 sns-card">
                    <div class="row pt-2 pr-2 pl-2 pb-2">
                        <div class="col">
                            <a href="{% url 'users:mypage' post.user.id %}">{{ post.user.username }}</a>

                            <span class="float-right">
                                {% if user == post.user %}
                                    <a href="{% url 'posts:delete' post.pk %}" class="btn btn-primary" style="margin-left: 15px;">삭제</a>
                                    <a href="{% url 'posts:update' post.pk %}" class="btn btn-primary">수정</a>
                                {% endif %}
                            </span>
                        </div>
                    </div>
                    {% if post.image %}
                        <img class="card-img-top" src="{{ post.image.url }}" alt="Card image cap">
                    {% endif %}
                    <div class="row">
                        <div class="col" style="margin-left:15px; margin-top: 5px;">
                            <span>
                                <a href="{% url 'posts:post_like' post.id %}" style="color: red;">
                                    {% if user in post.like_user_set.all %}
                                        <i class="fas fa-heart" style="font-size: 30px;"></i>
                                    {% else %}
                                        <i class="far fa-heart" style="font-size: 30px;"></i>
                                    {% endif %}
                                </a>
                            </span>
                            <span style="vertical-align: super;">{{ post.like_count }}명이 좋아합니다.</span>
                            <div class="follow-btn">
                                {% if user != post.user %}
                                    {% if user.profile in post.user.profile.followers.all %}
                                        <a href="{% url 'users:follow_toggle' post.user.id %}" class="btn btn-primary">팔로우 취소</a>
                                    {% else %}
                                        <a href="{% url 'users:follow_toggle' post.user.id %}" class="btn btn-outline-primary">팔로우</a>
                                    {% endif %}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="comment-section border-top">
                        {{ post.content }}
                            <form action="{% url 'posts:create_comment' post.id %}" method="POST" style="margin-top: 50px;" class="create-comment-form">
                                {% csrf_token %}
                                <div class="form-group">
                                    <textarea class="form-control" name="content" placeholder="댓글 달기..." required></textarea>
                                </div>
                                <button type="submit" class="btn btn-primary comment-submit-button">작성</button>
                            </form><br>
                            {% if post.comments %}
                                <ul class="list-group" id="comments-list-{{ post.pk }}" style="margin-top: 40px;">
                                    {% for comment in post.comments.all %}
                                        {% include 'comments/_comment.html' with comment=comment user=user %}
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="col-4">
            <div class="card mt-4 position-fixed">
                <div class="card-body">
                    {% if user.is_authenticated %}
                        <h5 class="card-title">{{ user.username }}님 환영합니다.</h5>
                        <a href="{% url 'users:mypage' user.id %}" class="btn btn-primary">마이페이지</a>
                    {% else %}
                        <a href="{% url 'account_login' %}" class="btn btn-primary">로그인</a>
                    {% endif %}
                </div>
                <div class="card-footer">
                    <small>
                    
                    © 2020 DJANGO_SNS FROM Jehoon
                    </small>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/shared/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light border-bottom">
    <div class="container">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'posts:create' %}">글 쓰기</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">로그아웃</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">마이페이지</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">로그인</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup'%}">회원가입</a>
                    </li>
                {% endif %}                
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

users/templates/users/mypage.html
{% extends 'base.html' %}

{% block content %}

<h1>{{ user.username}} 프로필</h1><br>
<h3>팔로워 {{ user.profile.followers.count }}명
</h3>
{% for follower in user.profile.followers.all %}
    {{ follower.user.username }}
{% endfor %}
<br>
<br>

<h3>팔로잉 {{ user.profile.followings.count }}명
</h3>
{% for following in user.profile.followings.all %}
    {{ following.user.username }}
{% endfor %}
<br>
<br><br>
{% for post in posts %}
    <div class="card mb-5 sns-card">
        <div class="row pt-2 pr-2 pl-2 pb-2">
            <div class="col">
                <a href="{% url 'users:mypage' post.user.id %}">{{ post.user.username }}</a>
                <span class="float-right">
                    {% if user == post.user %}
                        <a href="{% url 'posts:delete' post.pk %}" class="btn btn-primary" style="margin-left: 15px;">삭제</a>
                        <a href="{% url 'posts:update' post.pk %}" class="btn btn-primary">수정</a>
                    {% endif %}
                </span>
            </div>
        </div>
        {% if post.image %}
            <img class="card-img-top" src="{{ post.image.url }}" alt="Card image cap">
        {% endif %}
        <div class="row">
            <div class="col" style="margin-left:15px; margin-top: 5px;">
                <span>
                    <a href="{% url 'posts:post_like' post.id %}" style="color: red;">
                        {% if user in post.like_user_set.all %}
                            <i class="fas fa-heart" style="font-size: 30px;"></i>
                        {% else %}
                            <i class="far fa-heart" style="font-size: 30px;"></i>
                        {% endif %}
                    </a>
                </span>
                <span style="vertical-align: super;">{{ post.like_count }}명이 좋아합니다.</span>
                <div class="follow-btn">
                    {% if user != post.user %}
                        {% if user.profile in post.user.profile.followers.all %}
                            <a href="{% url 'users:follow_toggle' post.user.id %}" class="btn btn-primary">팔로우 취소</a>
                        {% else %}
                            <a href="{% url 'users:follow_toggle' post.user.id %}" class="btn btn-outline-primary">팔로우</a>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="comment-section border-top">
                {{ post.content }}
                <form action="{% url 'posts:create_comment' post.id %}" method="POST" style="margin-top: 50px;" class="create-comment-form">
                {% csrf_token %}
                    <div class="form-group">
                        <textarea class="form-control" name="content" placeholder="댓글 달기..." required></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary comment-submit-button">작성</button>
                </form><br>
                {% if post.comments %}
                    <ul class="list-group" id="comments-list-{{ post.pk }}" style="margin-top: 40px;">
                        {% for comment in post.comments.all %}
                            {% include 'comments/_comment.html' with comment=comment user=user %}
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
        </div>
    </div>
{% endfor %}

{% endblock %}